!FINDING THE DETERMINANT OF A MATRIX BY MAKING UPPER TRAINGULAR FORM
!TRHIS PROGRAM CAN FIND ANY TWO DIMENSIONAL SQUARE MATRIX DETERMINANT 

PROGRAM FIND_DET
  IMPLICIT NONE

REAL::MAT(1000,1000),TEMP,DET=1
INTEGER::N,I,J,K,L

PRINT*,"ENTER THE ROW NUMBER OF THE SQUARE MATRIX" 
 READ*,N

PRINT*,"ENTER THE ELEMENTS OF THE MATRIX BY ROW WISE"
DO I=1,N
 DO J=1,N
  READ*,MAT(I,J)
 END DO
END DO

PRINT*,"YOUR'S MATRIX IS:"
DO I=1,N
 PRINT*,(MAT(I,J),J=1,N)
END DO

!NOW NEXT STEP FIND OUT THE UPPER TRAINGULAR MATRIX
DO L=1,N-1
 DO I=L+1,N
  TEMP=MAT(I,L)/MAT(L,L)
  DO J=L,N
   MAT(I,J)=MAT(I,J)-TEMP*MAT(L,J)
  END DO
 END DO
END DO

PRINT*,"THE CORRESPONDING UPPER TRAINGULAR MATRIX IS:"
DO I=1,N
 PRINT*,(MAT(I,J),J=1,N)
END DO


!PRODUCT OF DIAGONAL TERMS
DO I=1,N
  DET=DET*MAT(I,I)
END DO
PRINT*,"THE REQUIRED DETERMINANT OF THE GIVEN MATRIX IS:",DET

END PROGRAM FIND_DET

